[package]
name = "gitconfig-https2git"
version = "0.1.0"
authors = ["jywww <jywww@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "1"
async-recursion = "1"
#futures-lite = "1"
anyhow = "1"
url = "2"
glob = "*"
futures = "0.3"
futures-async-stream = "0.2"
